### ISSUE TITLE
How to using on Kubernetes

### ISSUE THREAD

**Issue by Serrvosky** [cosmo0920/fluent-bit-go-loki#8]
#### Problem

Hello,

How can I use this plugin on Kubernetes? ow I can i instaill it on my fluentbit pods?

#### Using Fluentd and loki plugin versions

* OS version
Kubernetes
* fluent-bit version
fluent/fluent-bit:1.2.0
* fluent-bit-go-loki version
0.1.2
* Grafana and Loki version
??

**Comment by cosmo0920** [comment]
I'm not k8s guy.
I have no idea how to use this plugin on k8s.

**Comment by cosmo0920** [comment]
I have no idea what pod you are using to run fluent-bit.
But we can running fluent-git-go-loki plugin on Docker container like this PR:
https://github.com/cosmo0920/fluent-bit-go-loki/pull/10

To run k8s, we should use this built image in our k8s yaml settings:

```yaml
      containers:
      - name: fluent-bit
        image: fluent-bit/loki-plugin # Your built image
```
